# Generated by NeASM from example2.neasm
#
# The executed Python code:
#
# for n in range(4):
#   asm("paddq " + xmm[n+1] + ", " + xmm[n] + "")

paddq xmm1, xmm0
paddq xmm2, xmm1
paddq xmm3, xmm2
paddq xmm4, xmm3

