#!/usr/bin/env python

### Preprocessor ################################

import sys, re
from neasm import *
from registers import *


def preprocess(text, title = ''):
    program = []
    python_mode = False   # asm mode by default

    for line in text.splitlines():
        # Copy as-is spaces starting the line
        cmd = line.lstrip()
        spaces = line[0 : len(line) - len(cmd)]

        # Detect inversion of python_mode for the current line, or switch the global mode
        has_prefix  =  (cmd!="")  and  (cmd[0] == '%')
        if has_prefix:
            cmd = cmd[1:]
            if (cmd == 'python')  or  (cmd == 'asm'):
                python_mode = (cmd == 'python')
                continue

        # Add the command intact in the Python mode, or make it asm("...") call in the asm mode
        if python_mode ^ has_prefix:
            program.append(spaces + cmd)
        else:
            # Replace every "{expr}" occurence with result of `expr` evaluated as Python expression
            cmd = re.sub(r'[{](.+?)[}]', r'" + str(\1) + "', cmd)
            # Execute EQU meta-command
            matchobj = re.fullmatch(r'([\S]+)\s+([\S]+)\s+(.*)\s*', cmd)
            if matchobj:
                id,op,param = matchobj.group(1,2,3)
                if op.lower()=='equ':
                    equ(id,param)
                    cmd = cmt_char + ' ' + cmd
            # Output the final asm command
            program.append(spaces + "asm(\"" + cmd + "\")")

    print(title + cmt_char + ' The executed Python code:')
    print(cmt_char)
    for line in program:
        print(cmt_char + ' ' + line)
    print()

    exec('\n'.join(program))
    flush()


def preprocess_file(filename):
    with open(filename, encoding="utf-8") as f:
        title = cmt_char + ' Generated by NeASM preprocessor from ' + filename + '\n' + cmt_char + '\n'
        preprocess(f.read(), title)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Usage: nepp.py input.neasm >output.asm")
    else:
        preprocess_file(sys.argv[1])
