#!/usr/bin/env python

### Preprocessor ################################

import sys, re
from neasm import *
from registers import *


def preprocess(text, title = ''):
    program = []
    for line in text.splitlines():
        if (line=="")  or  (line[0] == '%'):
            program.append(line[1:])
        else:
            code = line.lstrip()
            spaces = len(line) - len(code)
            # Allow to use "{expr}" syntax to evaluate Python expressions inside assembler code
            code = re.sub(r'[{](.+?)[}]', r'" + \1 + "', code)
            program.append(line[0:spaces] + "asm(\"" + code + "\")")

    print(title + '# The executed Python code:')
    print('#')
    for line in program:
        print('# ' + line)
    print()

    exec('\n'.join(program))
    finish()


def preprocess_file(filename):
    with open(filename, encoding="utf-8") as f:
        title = '# Generated by NeASM preprocessor from ' + filename + '\n#\n'
        preprocess(f.read(), title)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Usage: nepp.py input.neasm >output.asm")
    else:
        preprocess_file(sys.argv[1])
