#!/usr/bin/env python

### Preprocessor ################################

import sys, re
from neasm import *
from registers import *


def preprocess(text, title = ''):
    program = []
    for line in text.splitlines():
        # Copy spaces, starting the line, intact to preserve the indentation structure
        code = line.lstrip()
        spaces = line[0 : len(line) - len(code)]
        if (code=="")  or  (code[0] == '%'):
            program.append(spaces + code[1:])
        else:
            # Allow to use "{expr}" syntax to evaluate Python expressions inside assembler code
            code = re.sub(r'[{](.+?)[}]', r'" + str(\1) + "', code)
            program.append(spaces + "asm(\"" + code + "\")")

    print(title + cmt_char + ' The executed Python code:')
    print(cmt_char)
    for line in program:
        print(cmt_char + ' ' + line)
    print()

    exec('\n'.join(program))
    flush()


def preprocess_file(filename):
    with open(filename, encoding="utf-8") as f:
        title = cmt_char + ' Generated by NeASM preprocessor from ' + filename + '\n' + cmt_char + '\n'
        preprocess(f.read(), title)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Usage: nepp.py input.neasm >output.asm")
    else:
        preprocess_file(sys.argv[1])
