# Generated by NeASM preprocessor from example3.neasm
#
# The executed Python code:
#
# # This is an example of using NeASM as Python-based preprocessor
# #   for regular assembler code.
# # Preprocess this file by running `nepp.py example3.neasm >example3.asm`
# asm("")
# asm("# hash_table equ r15")
# asm("# dict       equ r14")
# asm("# pos        equ r13")
# asm("# src_mask   equ [rsp+40]")
# asm("# hash_mask  equ [rsp+48]")
# asm("")
# asm("register src_8_bytes")
# asm("register hash_row")
# asm("")
# asm("mov src_8_bytes, [dict + pos]")
# asm("and src_8_bytes, src_mask")
# asm("xor hash_row, hash_row")
# asm("crc32 hash_row, src_8_bytes")
# asm("and hash_row, hash_mask")
# asm("")
# for n in range(4):
#     start_new_stream()
#     asm("register addr" + str(n) + "")
#     asm("mov addr" + str(n) + ", [hash_table + hash_row + " + str(n) + "*8]")
#     asm("prefetch [dict + addr" + str(n) + "]")
#     asm("prefetch [dict + addr" + str(n) + " + 31]")
# interleave_streams()


                                        # hash_table equ r15
                                        # dict       equ r14
                                        # pos        equ r13
                                        # src_mask   equ [rsp+40]
                                        # hash_mask  equ [rsp+48]

                                        # register src_8_bytes
                                        # register hash_row

mov rax, [r14 + r13]                    # mov src_8_bytes, [dict + pos]
and rax, [rsp+40]                       # and src_8_bytes, src_mask
xor rdx, rdx                            # xor hash_row, hash_row
crc32 rdx, rax                          # crc32 hash_row, src_8_bytes
and rdx, [rsp+48]                       # and hash_row, hash_mask

                                        # register addr0
                                        # register addr1
                                        # register addr2
                                        # register addr3
mov rax, [r15 + rdx + 0*8]              # mov addr0, [hash_table + hash_row + 0*8]
mov rbx, [r15 + rdx + 1*8]              # mov addr1, [hash_table + hash_row + 1*8]
mov rsi, [r15 + rdx + 2*8]              # mov addr2, [hash_table + hash_row + 2*8]
mov rdx, [r15 + rdx + 3*8]              # mov addr3, [hash_table + hash_row + 3*8]
prefetch [r14 + rax]                    # prefetch [dict + addr0]
prefetch [r14 + rbx]                    # prefetch [dict + addr1]
prefetch [r14 + rsi]                    # prefetch [dict + addr2]
prefetch [r14 + rdx]                    # prefetch [dict + addr3]
prefetch [r14 + rax + 31]               # prefetch [dict + addr0 + 31]
prefetch [r14 + rbx + 31]               # prefetch [dict + addr1 + 31]
prefetch [r14 + rsi + 31]               # prefetch [dict + addr2 + 31]
prefetch [r14 + rdx + 31]               # prefetch [dict + addr3 + 31]
